[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  
[build.environment]
  NODE_VERSION = "20"

# Test function
[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200

# API routes go to Netlify Functions (specific mappings)
[[redirects]]
  from = "/api/user/session"
  to = "/.netlify/functions/api-user-session"
  status = 200

[[redirects]]
  from = "/api/user/profile/*"
  to = "/.netlify/functions/api-user-profile"
  status = 200

[[redirects]]
  from = "/api/user/profile"
  to = "/.netlify/functions/api-user-profile"
  status = 200

[[redirects]]
  from = "/api/messages/generate"
  to = "/.netlify/functions/api-messages-generate"
  status = 200

# SPA routing - all other routes serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200