[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  
[build.environment]
  NODE_VERSION = "20"

# API routes go to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA routing - all other routes serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200